// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	context "context"

	metadata "google.golang.org/grpc/metadata"
	grpc_reflection_v1alpha "google.golang.org/grpc/reflection/grpc_reflection_v1alpha"

	mock "github.com/stretchr/testify/mock"
)

// ServerReflection_ServerReflectionInfoClient is an autogenerated mock type for the ServerReflection_ServerReflectionInfoClient type
type ServerReflection_ServerReflectionInfoClient struct {
	mock.Mock
}

type ServerReflection_ServerReflectionInfoClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ServerReflection_ServerReflectionInfoClient) EXPECT() *ServerReflection_ServerReflectionInfoClient_Expecter {
	return &ServerReflection_ServerReflectionInfoClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function with given fields:
func (_m *ServerReflection_ServerReflectionInfoClient) CloseSend() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerReflection_ServerReflectionInfoClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type ServerReflection_ServerReflectionInfoClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *ServerReflection_ServerReflectionInfoClient_Expecter) CloseSend() *ServerReflection_ServerReflectionInfoClient_CloseSend_Call {
	return &ServerReflection_ServerReflectionInfoClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *ServerReflection_ServerReflectionInfoClient_CloseSend_Call) Run(run func()) *ServerReflection_ServerReflectionInfoClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_CloseSend_Call) Return(_a0 error) *ServerReflection_ServerReflectionInfoClient_CloseSend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_CloseSend_Call) RunAndReturn(run func() error) *ServerReflection_ServerReflectionInfoClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with given fields:
func (_m *ServerReflection_ServerReflectionInfoClient) Context() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// ServerReflection_ServerReflectionInfoClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type ServerReflection_ServerReflectionInfoClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *ServerReflection_ServerReflectionInfoClient_Expecter) Context() *ServerReflection_ServerReflectionInfoClient_Context_Call {
	return &ServerReflection_ServerReflectionInfoClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *ServerReflection_ServerReflectionInfoClient_Context_Call) Run(run func()) *ServerReflection_ServerReflectionInfoClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_Context_Call) Return(_a0 context.Context) *ServerReflection_ServerReflectionInfoClient_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_Context_Call) RunAndReturn(run func() context.Context) *ServerReflection_ServerReflectionInfoClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with given fields:
func (_m *ServerReflection_ServerReflectionInfoClient) Header() (metadata.MD, error) {
	ret := _m.Called()

	var r0 metadata.MD
	var r1 error
	if rf, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServerReflection_ServerReflectionInfoClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type ServerReflection_ServerReflectionInfoClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *ServerReflection_ServerReflectionInfoClient_Expecter) Header() *ServerReflection_ServerReflectionInfoClient_Header_Call {
	return &ServerReflection_ServerReflectionInfoClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *ServerReflection_ServerReflectionInfoClient_Header_Call) Run(run func()) *ServerReflection_ServerReflectionInfoClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_Header_Call) Return(_a0 metadata.MD, _a1 error) *ServerReflection_ServerReflectionInfoClient_Header_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *ServerReflection_ServerReflectionInfoClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function with given fields:
func (_m *ServerReflection_ServerReflectionInfoClient) Recv() (*grpc_reflection_v1alpha.ServerReflectionResponse, error) {
	ret := _m.Called()

	var r0 *grpc_reflection_v1alpha.ServerReflectionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*grpc_reflection_v1alpha.ServerReflectionResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *grpc_reflection_v1alpha.ServerReflectionResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc_reflection_v1alpha.ServerReflectionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServerReflection_ServerReflectionInfoClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type ServerReflection_ServerReflectionInfoClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *ServerReflection_ServerReflectionInfoClient_Expecter) Recv() *ServerReflection_ServerReflectionInfoClient_Recv_Call {
	return &ServerReflection_ServerReflectionInfoClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *ServerReflection_ServerReflectionInfoClient_Recv_Call) Run(run func()) *ServerReflection_ServerReflectionInfoClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_Recv_Call) Return(_a0 *grpc_reflection_v1alpha.ServerReflectionResponse, _a1 error) *ServerReflection_ServerReflectionInfoClient_Recv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_Recv_Call) RunAndReturn(run func() (*grpc_reflection_v1alpha.ServerReflectionResponse, error)) *ServerReflection_ServerReflectionInfoClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *ServerReflection_ServerReflectionInfoClient) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerReflection_ServerReflectionInfoClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type ServerReflection_ServerReflectionInfoClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *ServerReflection_ServerReflectionInfoClient_Expecter) RecvMsg(m interface{}) *ServerReflection_ServerReflectionInfoClient_RecvMsg_Call {
	return &ServerReflection_ServerReflectionInfoClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *ServerReflection_ServerReflectionInfoClient_RecvMsg_Call) Run(run func(m interface{})) *ServerReflection_ServerReflectionInfoClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_RecvMsg_Call) Return(_a0 error) *ServerReflection_ServerReflectionInfoClient_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *ServerReflection_ServerReflectionInfoClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *ServerReflection_ServerReflectionInfoClient) Send(_a0 *grpc_reflection_v1alpha.ServerReflectionRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*grpc_reflection_v1alpha.ServerReflectionRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerReflection_ServerReflectionInfoClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type ServerReflection_ServerReflectionInfoClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *grpc_reflection_v1alpha.ServerReflectionRequest
func (_e *ServerReflection_ServerReflectionInfoClient_Expecter) Send(_a0 interface{}) *ServerReflection_ServerReflectionInfoClient_Send_Call {
	return &ServerReflection_ServerReflectionInfoClient_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *ServerReflection_ServerReflectionInfoClient_Send_Call) Run(run func(_a0 *grpc_reflection_v1alpha.ServerReflectionRequest)) *ServerReflection_ServerReflectionInfoClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*grpc_reflection_v1alpha.ServerReflectionRequest))
	})
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_Send_Call) Return(_a0 error) *ServerReflection_ServerReflectionInfoClient_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_Send_Call) RunAndReturn(run func(*grpc_reflection_v1alpha.ServerReflectionRequest) error) *ServerReflection_ServerReflectionInfoClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *ServerReflection_ServerReflectionInfoClient) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerReflection_ServerReflectionInfoClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type ServerReflection_ServerReflectionInfoClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *ServerReflection_ServerReflectionInfoClient_Expecter) SendMsg(m interface{}) *ServerReflection_ServerReflectionInfoClient_SendMsg_Call {
	return &ServerReflection_ServerReflectionInfoClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *ServerReflection_ServerReflectionInfoClient_SendMsg_Call) Run(run func(m interface{})) *ServerReflection_ServerReflectionInfoClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_SendMsg_Call) Return(_a0 error) *ServerReflection_ServerReflectionInfoClient_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_SendMsg_Call) RunAndReturn(run func(interface{}) error) *ServerReflection_ServerReflectionInfoClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function with given fields:
func (_m *ServerReflection_ServerReflectionInfoClient) Trailer() metadata.MD {
	ret := _m.Called()

	var r0 metadata.MD
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	return r0
}

// ServerReflection_ServerReflectionInfoClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type ServerReflection_ServerReflectionInfoClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *ServerReflection_ServerReflectionInfoClient_Expecter) Trailer() *ServerReflection_ServerReflectionInfoClient_Trailer_Call {
	return &ServerReflection_ServerReflectionInfoClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *ServerReflection_ServerReflectionInfoClient_Trailer_Call) Run(run func()) *ServerReflection_ServerReflectionInfoClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_Trailer_Call) Return(_a0 metadata.MD) *ServerReflection_ServerReflectionInfoClient_Trailer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerReflection_ServerReflectionInfoClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *ServerReflection_ServerReflectionInfoClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewServerReflection_ServerReflectionInfoClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewServerReflection_ServerReflectionInfoClient creates a new instance of ServerReflection_ServerReflectionInfoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServerReflection_ServerReflectionInfoClient(t mockConstructorTestingTNewServerReflection_ServerReflectionInfoClient) *ServerReflection_ServerReflectionInfoClient {
	mock := &ServerReflection_ServerReflectionInfoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
