// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: interceptor/testing/service_test.proto

package testing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	TestAuthenticatedMethodWithPermissionsOnly(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error)
	TestAuthenticatedMethodWithRolesOnly(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error)
	TestAuthenticatedMethodsWithRolesAndPermissions(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error)
	TestAuthenticatedMethodNoPermissionsAndRoles(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error)
	TestNotAuthenticatedMethodExplicit(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error)
	TestNotAuthenticatedMethodNoAnnotation(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) TestAuthenticatedMethodWithPermissionsOnly(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error) {
	out := new(TestMessage)
	err := c.cc.Invoke(ctx, "/interceptor.test.TestService/TestAuthenticatedMethodWithPermissionsOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) TestAuthenticatedMethodWithRolesOnly(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error) {
	out := new(TestMessage)
	err := c.cc.Invoke(ctx, "/interceptor.test.TestService/TestAuthenticatedMethodWithRolesOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) TestAuthenticatedMethodsWithRolesAndPermissions(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error) {
	out := new(TestMessage)
	err := c.cc.Invoke(ctx, "/interceptor.test.TestService/TestAuthenticatedMethodsWithRolesAndPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) TestAuthenticatedMethodNoPermissionsAndRoles(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error) {
	out := new(TestMessage)
	err := c.cc.Invoke(ctx, "/interceptor.test.TestService/TestAuthenticatedMethodNoPermissionsAndRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) TestNotAuthenticatedMethodExplicit(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error) {
	out := new(TestMessage)
	err := c.cc.Invoke(ctx, "/interceptor.test.TestService/TestNotAuthenticatedMethodExplicit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) TestNotAuthenticatedMethodNoAnnotation(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error) {
	out := new(TestMessage)
	err := c.cc.Invoke(ctx, "/interceptor.test.TestService/TestNotAuthenticatedMethodNoAnnotation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility
type TestServiceServer interface {
	TestAuthenticatedMethodWithPermissionsOnly(context.Context, *TestMessage) (*TestMessage, error)
	TestAuthenticatedMethodWithRolesOnly(context.Context, *TestMessage) (*TestMessage, error)
	TestAuthenticatedMethodsWithRolesAndPermissions(context.Context, *TestMessage) (*TestMessage, error)
	TestAuthenticatedMethodNoPermissionsAndRoles(context.Context, *TestMessage) (*TestMessage, error)
	TestNotAuthenticatedMethodExplicit(context.Context, *TestMessage) (*TestMessage, error)
	TestNotAuthenticatedMethodNoAnnotation(context.Context, *TestMessage) (*TestMessage, error)
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (UnimplementedTestServiceServer) TestAuthenticatedMethodWithPermissionsOnly(context.Context, *TestMessage) (*TestMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestAuthenticatedMethodWithPermissionsOnly not implemented")
}
func (UnimplementedTestServiceServer) TestAuthenticatedMethodWithRolesOnly(context.Context, *TestMessage) (*TestMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestAuthenticatedMethodWithRolesOnly not implemented")
}
func (UnimplementedTestServiceServer) TestAuthenticatedMethodsWithRolesAndPermissions(context.Context, *TestMessage) (*TestMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestAuthenticatedMethodsWithRolesAndPermissions not implemented")
}
func (UnimplementedTestServiceServer) TestAuthenticatedMethodNoPermissionsAndRoles(context.Context, *TestMessage) (*TestMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestAuthenticatedMethodNoPermissionsAndRoles not implemented")
}
func (UnimplementedTestServiceServer) TestNotAuthenticatedMethodExplicit(context.Context, *TestMessage) (*TestMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestNotAuthenticatedMethodExplicit not implemented")
}
func (UnimplementedTestServiceServer) TestNotAuthenticatedMethodNoAnnotation(context.Context, *TestMessage) (*TestMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestNotAuthenticatedMethodNoAnnotation not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_TestAuthenticatedMethodWithPermissionsOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).TestAuthenticatedMethodWithPermissionsOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interceptor.test.TestService/TestAuthenticatedMethodWithPermissionsOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).TestAuthenticatedMethodWithPermissionsOnly(ctx, req.(*TestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_TestAuthenticatedMethodWithRolesOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).TestAuthenticatedMethodWithRolesOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interceptor.test.TestService/TestAuthenticatedMethodWithRolesOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).TestAuthenticatedMethodWithRolesOnly(ctx, req.(*TestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_TestAuthenticatedMethodsWithRolesAndPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).TestAuthenticatedMethodsWithRolesAndPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interceptor.test.TestService/TestAuthenticatedMethodsWithRolesAndPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).TestAuthenticatedMethodsWithRolesAndPermissions(ctx, req.(*TestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_TestAuthenticatedMethodNoPermissionsAndRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).TestAuthenticatedMethodNoPermissionsAndRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interceptor.test.TestService/TestAuthenticatedMethodNoPermissionsAndRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).TestAuthenticatedMethodNoPermissionsAndRoles(ctx, req.(*TestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_TestNotAuthenticatedMethodExplicit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).TestNotAuthenticatedMethodExplicit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interceptor.test.TestService/TestNotAuthenticatedMethodExplicit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).TestNotAuthenticatedMethodExplicit(ctx, req.(*TestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_TestNotAuthenticatedMethodNoAnnotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).TestNotAuthenticatedMethodNoAnnotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interceptor.test.TestService/TestNotAuthenticatedMethodNoAnnotation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).TestNotAuthenticatedMethodNoAnnotation(ctx, req.(*TestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interceptor.test.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestAuthenticatedMethodWithPermissionsOnly",
			Handler:    _TestService_TestAuthenticatedMethodWithPermissionsOnly_Handler,
		},
		{
			MethodName: "TestAuthenticatedMethodWithRolesOnly",
			Handler:    _TestService_TestAuthenticatedMethodWithRolesOnly_Handler,
		},
		{
			MethodName: "TestAuthenticatedMethodsWithRolesAndPermissions",
			Handler:    _TestService_TestAuthenticatedMethodsWithRolesAndPermissions_Handler,
		},
		{
			MethodName: "TestAuthenticatedMethodNoPermissionsAndRoles",
			Handler:    _TestService_TestAuthenticatedMethodNoPermissionsAndRoles_Handler,
		},
		{
			MethodName: "TestNotAuthenticatedMethodExplicit",
			Handler:    _TestService_TestNotAuthenticatedMethodExplicit_Handler,
		},
		{
			MethodName: "TestNotAuthenticatedMethodNoAnnotation",
			Handler:    _TestService_TestNotAuthenticatedMethodNoAnnotation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interceptor/testing/service_test.proto",
}
